version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    extra_hosts:
      - 'website-cv-react.loc:0.0.0.0'
    ports:
      - 3000:3000
    labels:
      com.dnsdock.alias: website-cv-react.loc
